spring.application.name=ajax_app_java

# レンダーの環境変数（DATABASE_URL）を読み込む設定
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPAの設定（必要に応じて）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
