spring.application.name=ajax_app_java
spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver

# 元のこの形に戻してください（後ろのURLは消す）
spring.datasource.url=${SPRING_DATASOURCE_URL}

mybatis.configuration.map-underscore-to-camel-case=true